# Home-Manager Secret Helpers
#
# Reusable option types and helpers for modules that manage secrets
# with pluggable backends. Used by blackmatter-secrets.
#
# Usage:
#   secretHelpers = import "${substrate}/lib/hm-secret-helpers.nix" { inherit lib; };
#
#   options.myModule.secrets = lib.mkOption {
#     type = lib.types.attrsOf secretHelpers.secretSubmodule;
#   };
#
#   options.myModule.templates = lib.mkOption {
#     type = lib.types.attrsOf secretHelpers.templateSubmodule;
#   };
#
#   # Generate placeholders
#   myModule.placeholder = secretHelpers.mkPlaceholders "MYMOD" cfg.secrets;
#
#   # Resolve template content (inline or file)
#   content = secretHelpers.effectiveContent tmpl;
{ lib }:

rec {
  # ── Secret submodule ───────────────────────────────────────────────
  # Backend-agnostic secret declaration with permissions and ownership.
  secretSubmodule = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Target file path (empty = auto-generated by backend).";
      };
      mode = lib.mkOption {
        type = lib.types.str;
        default = "0400";
        description = "File permission mode (octal).";
      };
      owner = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "File owner (empty = current user).";
      };
      group = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "File group (empty = current group).";
      };
      restartUnits = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Systemd units to restart when this secret changes.";
      };
      reloadUnits = lib.mkOption {
        type = lib.types.listOf lib.types.str;
        default = [];
        description = "Systemd units to reload when this secret changes.";
      };
    };
  };

  # ── Template submodule ─────────────────────────────────────────────
  # Backend-agnostic template with placeholder substitution.
  templateSubmodule = lib.types.submodule {
    options = {
      path = lib.mkOption {
        type = lib.types.str;
        description = "Target file path for rendered template.";
      };
      content = lib.mkOption {
        type = lib.types.str;
        default = "";
        description = "Template content (use placeholders for secret values).";
      };
      file = lib.mkOption {
        type = lib.types.nullOr lib.types.path;
        default = null;
        description = "Template file (read at eval time, takes precedence over content).";
      };
      mode = lib.mkOption {
        type = lib.types.str;
        default = "0400";
      };
      owner = lib.mkOption { type = lib.types.str; default = ""; };
      group = lib.mkOption { type = lib.types.str; default = ""; };
    };
  };

  # ── Placeholder generation ─────────────────────────────────────────
  # Generate unique placeholders for each secret name.
  # prefix: module identifier (e.g., "BMSECRET", "AKEYLESS", "SOPS")
  mkPlaceholders = prefix: secrets:
    lib.mapAttrs (name: _:
      "<${prefix}:${builtins.hashString "sha256" name}:PLACEHOLDER>"
    ) secrets;

  # ── Template content resolution ────────────────────────────────────
  # If tmpl.file is set, read it at eval time. Otherwise use tmpl.content.
  effectiveContent = tmpl:
    if tmpl.file != null then builtins.readFile tmpl.file else tmpl.content;

  # ── Placeholder substitution ───────────────────────────────────────
  # Replace unified placeholders in a string with backend-specific ones.
  # unifiedPlaceholders: the source module's placeholder map
  # backendPlaceholders: the target backend's placeholder map
  # keyTransform: function to transform secret name → backend key
  substitutePlaceholders = { content, secrets, unifiedPlaceholders, backendPlaceholders, keyTransform ? (x: x) }:
    lib.foldlAttrs (acc: name: _:
      builtins.replaceStrings
        [ (unifiedPlaceholders.${name} or "") ]
        [ (backendPlaceholders.${keyTransform name} or "") ]
        acc
    ) content secrets;
}
