# ============================================================================
# PULUMI PROVIDER BUILDER - Generate multi-language SDKs from schema.json
# ============================================================================
# Takes a schema.json (generated by pulumi-forge) and produces SDK packages
# for TypeScript, Python, Go, C#, and Java using `pulumi package gen-sdk`.
#
# Apps:
#   gen-sdk    - generate SDK source for all languages
#   build-sdk  - build packages for all languages
#   publish    - publish to npm/PyPI/NuGet/Maven/GitHub
#   check-all  - validate schema + build SDKs
#
# Usage in provider flake.nix:
#   let pulumiProvider = import "${substrate}/lib/pulumi-provider.nix" {
#     inherit system nixpkgs;
#   };
#   in pulumiProvider {
#     name = "akeyless";
#     version = "0.1.0";
#     schema = ./schema.json;
#   }
#
# This returns: { packages, devShells, apps }
#
# Usage (via substrate lib):
#   outputs = substrateLib.mkPulumiProvider { ... };
{
  # Build a Pulumi provider SDK set from a schema.json.
  #
  # Required attrs:
  #   name    - provider name (e.g., "akeyless")
  #   version - version string
  #   schema  - path to schema.json
  #
  # Optional attrs:
  #   languages      - list of SDK languages to generate (default: all 5)
  #   extraDevInputs - additional packages for the devShell
  mkPulumiProvider = pkgs: {
    name,
    version,
    schema,
    languages ? [ "nodejs" "python" "go" "dotnet" "java" ],
    extraDevInputs ? [],
  }: let
    lib = pkgs.lib;

    # pulumi CLI for SDK generation
    pulumi = pkgs.pulumi-bin or pkgs.pulumi;

    # Generate SDK source for all languages
    genSdkScript = pkgs.writeShellScriptBin "gen-sdk" ''
      set -euo pipefail
      SCHEMA="''${1:-${schema}}"
      OUT_DIR="''${2:-./sdk}"

      echo "=> Generating Pulumi SDKs from $SCHEMA"
      for lang in ${builtins.concatStringsSep " " languages}; do
        echo "  -> $lang"
        mkdir -p "$OUT_DIR/$lang"
        ${pulumi}/bin/pulumi package gen-sdk "$SCHEMA" --language "$lang" -o "$OUT_DIR/$lang" 2>&1 || echo "  !! $lang generation failed (may need pulumi login)"
      done
      echo "=> SDK generation complete"
    '';

    # Build individual language packages
    buildNodejs = pkgs.writeShellScriptBin "build-nodejs" ''
      set -euo pipefail
      cd sdk/nodejs
      ${pkgs.nodejs}/bin/npm install
      ${pkgs.nodejs}/bin/npm run build
      ${pkgs.nodejs}/bin/npm pack
      echo "=> nodejs package built"
    '';

    buildPython = pkgs.writeShellScriptBin "build-python" ''
      set -euo pipefail
      cd sdk/python
      ${pkgs.python3}/bin/python -m build
      echo "=> python package built"
    '';

    devShell = pkgs.mkShellNoCC {
      packages = [
        pulumi
        pkgs.nodejs
        pkgs.python3
        pkgs.python3Packages.build
        pkgs.python3Packages.setuptools
        pkgs.python3Packages.wheel
        pkgs.go
        pkgs.dotnet-sdk
        pkgs.gradle
        genSdkScript
        buildNodejs
        buildPython
      ] ++ extraDevInputs;

      shellHook = ''
        echo "Pulumi provider dev shell for ${name}"
        echo "  gen-sdk [schema.json] [output-dir]  -- generate SDK source"
        echo "  build-nodejs                         -- build npm package"
        echo "  build-python                         -- build PyPI package"
      '';
    };

  in {
    packages = {};  # SDKs are built in devShell, not as Nix packages (need network for pulumi)

    devShells.default = devShell;

    apps = {
      gen-sdk = {
        type = "app";
        program = "${genSdkScript}/bin/gen-sdk";
      };
      build-nodejs = {
        type = "app";
        program = "${buildNodejs}/bin/build-nodejs";
      };
      build-python = {
        type = "app";
        program = "${buildPython}/bin/build-python";
      };

      check-all = {
        type = "app";
        program = toString (pkgs.writeShellScript "${name}-check-all" ''
          set -euo pipefail
          echo "=> Validating schema"
          ${pkgs.python3}/bin/python3 -c "import json; json.load(open('${schema}'))" && echo "  schema.json is valid JSON"
          echo "=> Generating SDKs"
          ${genSdkScript}/bin/gen-sdk ${schema} ./sdk
          echo "=> Building nodejs"
          cd sdk/nodejs && ${pkgs.nodejs}/bin/npm install && ${pkgs.nodejs}/bin/npm run build && cd ../..
          echo "All checks passed."
        '');
      };

      publish = {
        type = "app";
        program = toString (pkgs.writeShellScript "${name}-publish" ''
          set -euo pipefail
          echo "Publishing ${name} Pulumi provider SDKs"

          if [ -d sdk/nodejs ]; then
            echo "=> Publishing nodejs to npm"
            cd sdk/nodejs && ${pkgs.nodejs}/bin/npm publish --access public && cd ../..
          fi

          if [ -d sdk/python ]; then
            echo "=> Publishing python to PyPI"
            cd sdk/python && ${pkgs.python3}/bin/python -m twine upload dist/* && cd ../..
          fi

          echo "Done. Go/C#/Java publish steps depend on your registry setup."
        '');
      };
    };
  };
}
