name: publish-flakehub

on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          sparse-checkout: |
            flake.nix
            flake.lock
          sparse-checkout-cone-mode: false

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Publish to FlakeHub
        uses: DeterminateSystems/flakehub-push@main
        with:
          visibility: public
          rolling: true